name: CI

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 13 * * 1"

jobs:  
  test-e2e:
    name: Test Extension with Sunbeam
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Test with Sunbeam
        uses: sunbeam-labs/sbx_test_action@v0
        with:
          sunbeam-version: 'dev'
          extension-name: 'sunbeam-labs/sbx_kraken'
          extension-branch-name: ${{ github.head_ref }}
          test-directory: '.tests/e2e/'
